apiVersion: apps/v1beta2 #apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: k8s-go-threads
  labels:
    app: threads
spec:
  replicas: 3
  selector:
    matchLabels:
      app: threads
  template:
    metadata:
      labels:
        app: threads
    spec:
      containers:
      - name: k8s-go-threads
        image: k8s-go-threads:0.1
