/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	trailhead_v1 "github.com/ropes/k8s-trailhead/pkg/apis/trailhead/v1"
	versioned "github.com/ropes/k8s-trailhead/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ropes/k8s-trailhead/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ropes/k8s-trailhead/pkg/client/listers/trailhead/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SimpleSpecInformer provides access to a shared informer and lister for
// SimpleSpecs.
type SimpleSpecInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SimpleSpecLister
}

type simpleSpecInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSimpleSpecInformer constructs a new informer for SimpleSpec type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSimpleSpecInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSimpleSpecInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSimpleSpecInformer constructs a new informer for SimpleSpec type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSimpleSpecInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrailheadV1().SimpleSpecs(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrailheadV1().SimpleSpecs(namespace).Watch(options)
			},
		},
		&trailhead_v1.SimpleSpec{},
		resyncPeriod,
		indexers,
	)
}

func (f *simpleSpecInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSimpleSpecInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *simpleSpecInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&trailhead_v1.SimpleSpec{}, f.defaultInformer)
}

func (f *simpleSpecInformer) Lister() v1.SimpleSpecLister {
	return v1.NewSimpleSpecLister(f.Informer().GetIndexer())
}
